# Exercise 3: Data Structures, Functions and Loops

In this week's exercise, you'll learn how to:

1. write functions that manipulate data structures such as lists and dictionaries
2. master list comprehension and dict comprehension
3. compute operations on matrices represented as lists of lists

## Lists

### 3.1 Write a Python function to sum all the numbers in a list.

Write a function to sum all number in a list without using the `sum()` built-in method. Hint: use a `for..in` cycle instead.

Sample list: `[9, 12, 7, 19]`

Expected output: 47

In [2]:
# Write your function here:
# Hint: do not use the name `sum` for your function because it would overwrite the built-in sum() method
# Defining the function
def sum_numbers(numbers):
    # Initializing a variable to store the sum
    total = 0
    
    # Iterating through the list
    for num in numbers:
        total += num  # Adds each number to the total
    
    return total  # This returns the computed sum

# Test
sample_list = [9, 12, 7, 19]
result = sum_numbers(sample_list)

# printing the Results 
print(f"The sum of the numbers in the list {sample_list} is: {result}")

The sum of the numbers in the list [9, 12, 7, 19] is: 47


In [5]:
# Test your function here
def sum_numbers(numbers):
    # Initializing a variable to store the sum
    total = 0
    
    # Iterating through the list
    for num in numbers:
        total += num  # Adds each number to the total
    
    return total  # This returns the computed sum

# Test
list = [9, 12, 7, 19]
result = sum_numbers(list)

# printing the Results 
print(f"The sum of the numbers in the list {list} is: {result}")


The sum of the numbers in the list [9, 12, 7, 19] is: 47


### 3.2 Write a Python program to count the number of elements in a list within a specified range.

Sample list: `[10,20,30,40,40,40,70,80,99]`

Sample min: `15`

Sample max: `50`

Expected output: `5`

In [4]:
# Write your function here:
sample_list=[10,20,30,40,40,40,70,80,99]
sample_min=15
sample_max=50
sample_list.count(40)


3

In [5]:
# Define the function to count elements in the specified range
def count_in_range(numbers, min_value, max_value):
    count = 0  # Initialize a counter
    for num in numbers:  # Iterate through the list
        if min_value <= num <= max_value:  # Check if the number is in range
            count += 1  # Increment the counter if it is
    return count  # Return the final count

# Sample list and range
sample_list = [10, 20, 30, 40, 40, 40, 70, 80, 99]
sample_min = 15
sample_max = 50

# Call the function and print the result
result = count_in_range(sample_list, sample_min, sample_max)
print(f"The number of elements in the range {sample_min} to {sample_max} is: {result}")


The number of elements in the range 15 to 50 is: 5


In [6]:
# Test your function here
# Define the function to count elements in the specified range
def count_in_range(numbers, min_value, max_value):
    count = 0  # Initialize a counter
    for num in numbers:  # Iterate through the list
        if min_value <= num <= max_value:  # Check if the number is in range
            count += 1  # Increment the counter if it is
    return count  # Return the final count

# Sample list and range
sample_list = [10, 20, 30, 40, 40, 40, 70, 80, 99]
sample_min = 15
sample_max = 50

# Call the function and print the result
result = count_in_range(sample_list, sample_min, sample_max)
print(f"The number of elements in the range {sample_min} to {sample_max} is: {result}")


The number of elements in the range 15 to 50 is: 5


### 3.3 List Manipulation

From the given list:

```
gadgets = [“Mobile”, “Laptop”, 100, “Camera”, 310.28, “Speakers”, 27.00,
“Television”, 1000, “Laptop Case”, “Camera Lens”]
```

a)create separate lists of strings and numbers.
 
b)Sort the strings list in ascending order
 
c)Sort the strings list in descending order
 
d)Sort the number list from lowest to highest
 
e)Sort the number list from highest to lowest

In [3]:
# Write your solution here:

gadgets = ["Mobile", "Laptop", 100, "Camera", 310.28, "Speakers", 27.00, 
           "Television", 1000, "Laptop Case", "Camera Lens"]
 

# Write your solutions here 
 
# a)creating separate lists

string_list = []
number_list = []
for item in gadgets:
    if isinstance(item, str):
        string_list.append(item)
    elif isinstance(item, (int, float)):
        number_list.append(item)    
print(string_list)
print(number_list)
 
# b)sorting strings list in ascending order, a-z

string_list.sort()
print(string_list)

number_list.sort()
print(number_list)

# c)sorting strings list in descending order z-a
  
# d)sorting number list from lowest to highest
 
# e)sorting number list from highest to lowest
 

['Mobile', 'Laptop', 'Camera', 'Speakers', 'Television', 'Laptop Case', 'Camera Lens']
[100, 310.28, 27.0, 1000]
['Camera', 'Camera Lens', 'Laptop', 'Laptop Case', 'Mobile', 'Speakers', 'Television']


In [1]:
# Given list
gadgets = ["Mobile", "Laptop", 100, "Camera", 310.28, "Speakers", 27.00, 
           "Television", 1000, "Laptop Case", "Camera Lens"]

# a) Creating separate lists for strings and numbers
string_list = []
number_list = []

for item in gadgets:
    if isinstance(item, str):  # Check if the item is a string
        string_list.append(item)
    elif isinstance(item, (int, float)):  # Check if the item is a number
        number_list.append(item)

print("Strings List:", string_list)
print("Numbers List:", number_list)

# b) Sorting the strings list in ascending order (a-z)
string_list.sort()
print("Strings List (Ascending):", string_list)

# c) Sorting the strings list in descending order (z-a)
string_list.sort(reverse=True)
print("Strings List (Descending):", string_list)

# d) Sorting the number list from lowest to highest
number_list.sort()
print("Numbers List (Ascending):", number_list)

# e) Sorting the number list from highest to lowest
number_list.sort(reverse=True)
print("Numbers List (Descending):", number_list)


Strings List: ['Mobile', 'Laptop', 'Camera', 'Speakers', 'Television', 'Laptop Case', 'Camera Lens']
Numbers List: [100, 310.28, 27.0, 1000]
Strings List (Ascending): ['Camera', 'Camera Lens', 'Laptop', 'Laptop Case', 'Mobile', 'Speakers', 'Television']
Strings List (Descending): ['Television', 'Speakers', 'Mobile', 'Laptop Case', 'Laptop', 'Camera Lens', 'Camera']
Numbers List (Ascending): [27.0, 100, 310.28, 1000]
Numbers List (Descending): [1000, 310.28, 100, 27.0]


## Dictionaries



### 3.4 Dictionary manipulation

Write a function that takes a dictionary as input and retuns the mean (i.e. average value) of the values stored in the dictionary

```
Sample Dictionary = Life expectancy by country = {
    'Japan': 83.7,
    'Switzerland': 83.4,
    'Singapore': 83.1,
    'Italy': 82.7,
    'Israel': 82.5,
    'Netherlands': 81.9,
    'United Kingdom': 81.2,
    'Cyprus': 80.5,
    'Chile': 80.5,
    'United States: 79.3,
    'Argentina': 76.3,
    'Iran': 75.5,
    'Jordan': 74.1,
    'Russia': 70.5,
    'Philippines': 68.5,
    'India': 68.3
}
```

In [4]:
# Write your function here:




In [3]:
# Test your code here:
# Define the function
def calculate_mean(dictionary):
    # Ensure the dictionary is not empty to avoid division by zero
    if not dictionary:
        return 0
    
    # Calculate the mean: sum of values divided by the number of values
    mean_value = sum(dictionary.values()) / len(dictionary)
    
    return mean_value

# Sample Dictionary: Life expectancy by country
life_expectancy = {
    'Japan': 83.7,
    'Switzerland': 83.4,
    'Singapore': 83.1,
    'Italy': 82.7,
    'Israel': 82.5,
    'Netherlands': 81.9,
    'United Kingdom': 81.2,
    'Cyprus': 80.5,
    'Chile': 80.5,
    'United States': 79.3,
    'Argentina': 76.3,
    'Iran': 75.5,
    'Jordan': 74.1,
    'Russia': 70.5,
    'Philippines': 68.5,
    'India': 68.3
}

# Calculate and print the mean life expectancy
mean_life_expectancy = calculate_mean(life_expectancy)
print(f"The mean life expectancy is: {mean_life_expectancy:.2f}")


The mean life expectancy is: 78.25


### 3.5 Dictionary sorting

Write a program that sorts by key in descending order (from Z to A) the dictionary of **exercise 3.4**. 

Hint: inspect the Python built-in functions (https://docs.python.org/3.7/library/functions.html)

In [20]:
# Write your program here


### 3.6 Lists to Dictionary

Write a program (or function) that maps two lists into a dictionary

Sample first list: ```['Japan', 'Italy', 'United Kingdom', 'Russia']```

Sample second list: ```[83.7, 82.7, 81.2, 70.5]```

In [21]:
# Write your program here


In [5]:
# Define the function to map two lists into a dictionary
def lists_to_dict(keys, values):
    # Use the zip function to pair keys and values, then convert to a dictionary
    return dict(zip(keys, values))

# Sample lists
countries = ['Japan', 'Italy', 'United Kingdom', 'Russia']
life_expectancies = [83.7, 82.7, 81.2, 70.5]

# Call the function and create the dictionary
country_life_expectancy = lists_to_dict(countries, life_expectancies)

# Print the resulting dictionary
print(country_life_expectancy)


{'Japan': 83.7, 'Italy': 82.7, 'United Kingdom': 81.2, 'Russia': 70.5}


Explanation
zip() Function:

zip(keys, values) pairs each element in the keys list with the corresponding element in the values list.
Example: zip(['Japan', 'Italy'], [83.7, 82.7]) produces [('Japan', 83.7), ('Italy', 82.7)].
Convert to Dictionary:

dict(zip(keys, values)) converts the paired elements into a dictionary.
Flexible Input:

The function works for any two lists of equal length. If the lengths are not equal, zip will only pair up to the shorter length.

## Tuples

### 3.7 Write a Python program to get the 4th element and 4th element from last of a tuple.

Sample input

```
tuplex = ("we", 3, "are", "left", 4.8, "our", "u", "www.ox.ac.uk", "core", "empty")
```

In [22]:
# Write your solution here 


In [1]:
# Sample input tuple
tuplex = ("we", 3, "are", "left", 4.8, "our", "u", "www.ox.ac.uk", "core", "empty")

# Geting the 4th element (index 3, as indexing starts at 0)
fourth_element = tuplex[3]

# Get the 4th element from the last (index -4)
fourth_from_last_element = tuplex[-4]

# Print the results
print(f"The 4th element is: {fourth_element}")
print(f"The 4th element from the last is: {fourth_from_last_element}")


The 4th element is: left
The 4th element from the last is: u


Explanation
4th Element:

Indexing in Python starts at 0, so the 4th element is at index 3.
tuplex[3] retrieves the element at this position.
4th Element from the Last:

Negative indexing allows counting from the end of the tuple.
tuplex[-4] retrieves the 4th element from the last.
Output:

The program prints both the 4th element and the 4th element from the last.

### 3.8  Write a Python program to convert a list of tuples to a dictionary.

Sample input: ```[(28, 'February'), (30, 'April'), (31, 'July'), (31, 'August'), (30, 'November')]```

Sample output ```{'February': 28, 'April': 30, 'July': 31, 'August': 31, 'November': 30}```

In [23]:
# Write your program here


In [2]:
# Sample input: list of tuples
tuples_list = [(28, 'February'), (30, 'April'), (31, 'July'), (31, 'August'), (30, 'November')]

# Convert the list of tuples to a dictionary
# Use a dictionary comprehension where the second element of the tuple is the key and the first is the value
result_dict = {month: days for days, month in tuples_list}

# Print the resulting dictionary
print(result_dict)


{'February': 28, 'April': 30, 'July': 31, 'August': 31, 'November': 30}


Explanation
Input List of Tuples:

The list contains tuples where the first element is the value (number of days) and the second is the key (month).
Dictionary Comprehension:

{month: days for days, month in tuples_list}:
Iterates over each tuple in the list.
Assigns the second element (month) as the key.
Assigns the first element (days) as the value.
Output the Result:

Prints the dictionary.

## `for` loops, list comprehension, dict comprehension

### 3.9 List comprehension

Rewrite the following code using list comprehension

In [24]:
# Code to be rewritten

sentence = "the quick brown fox jumps over the lazy dog"
words = sentence.split()
word_lengths = []
for word in words:
      if word != "the":
          word_lengths.append(len(word))
print(words)
print(word_lengths)

['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
[5, 5, 3, 5, 4, 4, 3]


In [1]:
# Write your solution here
# Original sentence
sentence = "the quick brown fox jumps over the lazy dog"

# List comprehension to compute word lengths, excluding the word "the"
words = sentence.split()
word_lengths = [len(word) for word in words if word != "the"]

# Print the results
print(words)
print(word_lengths)


['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
[5, 5, 3, 5, 4, 4, 3]


Explanation
Splitting the Sentence:

words = sentence.split() splits the sentence into a list of words.
List Comprehension:

[len(word) for word in words if word != "the"]:
Iterates over each word in words.
Excludes the word "the" using the condition if word != "the".
Appends the length of each remaining word (len(word)) to the word_lengths list.
Printing Results:

words: Contains all the words from the sentence.
word_lengths: Contains the lengths of the words, excluding "the".

### 3.10 List filtering

Using a list comprehension, create a new list called "newlist" out of the list "numbers", which contains only the positive numbers from the list, as integers rounded to the closest integer value.

In [26]:
### Input

numbers = [34.6, -203.4, 44.9, 68.3, -12.2, 44.6, 12.7]

### Write your solution here


In [2]:
# Input list
numbers = [34.6, -203.4, 44.9, 68.3, -12.2, 44.6, 12.7]

# Using list comprehension to filter and round positive numbers
newlist = [round(num) for num in numbers if num > 0]

# Print the resulting list
print(newlist)


[35, 45, 68, 45, 13]


Explanation
Filter Positive Numbers:

The condition if num > 0 ensures only positive numbers from numbers are included.
Round the Numbers:

The round(num) function rounds the number to the nearest integer.
List Comprehension:

Combines the filtering and rounding in one line

### 3.11 Matrix Element Wise-multiplication

Matrices can be encoded as numerical two-dimensional lists
Consider the two following matrices 

```
mat_00 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
```
and
```
mat_01 = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
```

Compute the element-wise multiplication of the two matrices, i.e.

```
mat_02 = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
```

In [27]:
mat_00 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mat_01 = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

## Write your solution here:


### 3.12 Matrix-Matrix Multiplication

Consider the following two matrices

```
mat_00 = [[2, 1, 3], [1, 1, 2]]
```
and
```
A = [[1, 2], [5, 6], [7, 9]]
```

Compute the matrix multiplication, i.e.:
```
B = [[28 37] [20 26]]
```



In [28]:
A = [[2, 1, 3], [1, 1, 2]]
B = [[1, 2], [5, 6], [7, 9]]

# Write your solution here


### 3.13 Dict comprehension

Consider these four lists:
```
fellowship_names = ['gandalf', 'frodo', 'samwise', 'merry', 'aragorn', 'legolas', 'boromir', 'gimli', 'pippin']
```
```
fellowship_surnames = [
    'mithrandir', 'baggins', 'gamgee', 'brandybuck', 'elessar', 
    'greenleaf', 'son of denethor', 'son of gloin', 'took'
]
```
```
fellowship_species = ['maia', 'hobbit', 'hobbit', 'hobbit', 'man', 'elf', 'man', 'dwarf', 'hobbit']
```
```
fellowship_ages = [inf, 51, 36, 37, 88, 800, 41, 140, 29]
```

1) Produce a dictionary with the mapping `fellowship_name` -> `fellowship_age`, pairing each element with the same index in the two lists

2) Produce a dictionary with the mapping `(fellowship_name, fellowship_surname)` -> `fellowship_species`, pairing each element with the same index in the three lists

In [29]:
from math import inf

fellowship_names = ['gandalf', 'frodo', 'samwise', 'merry', 'aragorn', 
                    'legolas', 'boromir', 'gimli', 'pippin']
fellowship_surnames = [
    'mithrandir', 'baggins', 'gamgee', 'brandybuck', 'elessar', 
    'greenleaf', 'son of denethor', 'son of gloin', 'took'
]
fellowship_species = ['maia', 'hobbit', 'hobbit', 'hobbit', 'man', 'elf', 'man', 'dwarf', 'hobbit']

fellowship_ages = [inf, 51, 36, 37, 88, 800, 41, 140, 29]

# Write your solution here
